#!/bin/sh
# shellcheck disable=SC2016,SC2039

set -eu

VERSION="v2.5.1"
URL="https://github.com/ko1nksm/getoptions"
LICENSE="Creative Commons Zero v1.0 Universal"

if [ "${KSH_VERSION:-}" ] || [ "${ZSH_VERSION:-}" ]; then
	putlines() { IFS=$'\n'$IFS; print -r -- "$*"; IFS=${IFS#?}; }
else
	putlines() { printf '%s\n' "$@"; }
fi

outlibs() {
	cat lib/getoptions_base.sh # @INCLUDE-FILE
	cat lib/getoptions_abbr.sh # @INCLUDE-FILE
	cat lib/getoptions_help.sh # @INCLUDE-FILE
}

quote() {
	q="$2'" r=''
	while [ "$q" ]; do r="$r${q%%\'*}'\''" && q=${q#*\'}; done
	q="'${r%????}'" && q=${q#\'\'} && q=${q%\'\'}
	eval "$1=\${q:-\"''\"}"
}

case ${1:-} in (-?* | '')
	echo "getoptions $VERSION ($URL)"
	echo "License: $LICENSE"
	echo 'Usage: eval "$(getoptions <parser_definition> <parser_name> [arguments...])"'
	exit ${1:+1}
esac

outlibs
[ "$1" = - ] && exit 0
for i; do
	quote i "$i"
	set -- "$@" "$i"
	shift
done
echo "eval \"\$(getoptions $*)\""
