name: Coverage

on: [push]

env:
  FORCE_COLOR: 1

jobs:
  ubuntu-jammy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y bash kcov
    - name: Install shellspec
      run: |
        echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
        curl -fsSL https://git.io/shellspec | sh -s master -y
    - name: Check code
      run: make check_with_docker
    - name: Measure code coverage
      run: make test_with_coverage
    - name: Send code coverage
      uses: codecov/codecov-action@v4
      with:
        directory: coverage
        fail_ci_if_error: true
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
